package cn.xyz.io.mogan.entity;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mogan..test.test_id
     *
     * @mbggenerated Wed Mar 27 19:53:30 CST 2019
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mogan..test.name
     *
     * @mbggenerated Wed Mar 27 19:53:30 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mogan..test.test_id
     *
     * @return the value of mogan..test.test_id
     *
     * @mbggenerated Wed Mar 27 19:53:30 CST 2019
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mogan..test.test_id
     *
     * @param testId the value for mogan..test.test_id
     *
     * @mbggenerated Wed Mar 27 19:53:30 CST 2019
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mogan..test.name
     *
     * @return the value of mogan..test.name
     *
     * @mbggenerated Wed Mar 27 19:53:30 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mogan..test.name
     *
     * @param name the value for mogan..test.name
     *
     * @mbggenerated Wed Mar 27 19:53:30 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}